export type InputName =
	"BUILD_OR_DELETE_INPUT"
	| "ROTATE_BUILD_INPUT"
	| "DELETE_MODE_INPUT"
	| "BLOCK_1_INPUT"
	| "BLOCK_2_INPUT"
	| "BLOCK_3_INPUT"
	| "BLOCK_4_INPUT"
	| "BLOCK_5_INPUT"

return {
	"BUILD_OR_DELETE_INPUT",
	"ROTATE_BUILD_INPUT",
	"DELETE_MODE_INPUT",
	"BLOCK_1_INPUT",
	"BLOCK_2_INPUT",
	"BLOCK_3_INPUT",
	"BLOCK_4_INPUT",
	"BLOCK_5_INPUT",
}
